#!/usr/bin/env node
/**
 * Fetches book covers from Open Library ONCE and commits them to
 * `public/covers/{id}.jpg`, then writes the manifest `src/data/covers.ts`.
 *
 *   node scripts/fetch-covers.mjs [--force]
 *
 * Fetching at build time rather than hotlinking is deliberate: the site claims
 * "no tracking, no cookies, no analytics" in its colophon, and hotlinking would
 * hand every visitor's IP to a third party. It also means a cover can never
 * 404 in front of a reader.
 *
 * Coverage is imperfect — ISBN lookups miss for a good share of the shelf — so
 * the UI must keep its typographic fallback for anything not in the manifest.
 * The script is idempotent: it skips covers already on disk unless --force.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { books } from '../src/data/books.ts'

const COVERS = resolve(import.meta.dirname, '..', 'public', 'covers')
const MANIFEST = resolve(import.meta.dirname, '..', 'src', 'data', 'covers.ts')
const force = process.argv.includes('--force')

// Open Library asks for a contactable User-Agent and modest request rates.
const HEADERS = { 'User-Agent': 'tomplum-profile/1.0 (https://github.com/TomPlum/profile)' }
const PAUSE_MS = 250

const sleep = (ms) => new Promise((done) => setTimeout(done, ms))

/** A cover-shaped response: 200, image/*, and big enough to be real artwork. */
const readImage = async (url) => {
  const response = await fetch(url, { headers: HEADERS })

  if (response.status === 429 || response.status === 403) {
    console.log('  rate limited — waiting 60s')
    await sleep(60_000)
    return readImage(url)
  }
  if (!response.ok) return undefined
  if (!(response.headers.get('content-type') ?? '').startsWith('image/')) return undefined

  const bytes = Buffer.from(await response.arrayBuffer())
  return bytes.byteLength > 2_000 ? bytes : undefined
}

const byIsbn = async (isbn) =>
  isbn ? readImage(`https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg?default=false`) : undefined

const normalise = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()

/**
 * Last resort: ask the search index for a cover id by title + author.
 *
 * Constrained to English editions and to results whose title actually matches
 * — an unfiltered search happily returns a Spanish translation of Red Rising,
 * or a box-set collage of the whole Witcher series, and both look like a bug
 * rather than a book on the shelf.
 */
const bySearch = async (book) => {
  const query = new URLSearchParams({
    title: book.title,
    author: book.author,
    language: 'eng',
    limit: '8',
    fields: 'key,title'
  })
  const response = await fetch(`https://openlibrary.org/search.json?${query}`, { headers: HEADERS })
  if (!response.ok) return undefined

  const { docs = [] } = await response.json()
  const wanted = normalise(book.title)
  const work = docs.find((doc) => {
    if (!doc.key || !doc.title) return false
    const found = normalise(doc.title)
    return found === wanted || found.startsWith(wanted) || wanted.startsWith(found)
  })
  if (!work) return undefined

  // The work's default cover is whichever edition Open Library happens to
  // prefer — often a translation. Walk the editions for an English one that
  // carries its own artwork instead.
  await sleep(PAUSE_MS)
  const editions = await fetch(`https://openlibrary.org${work.key}/editions.json?limit=50`, {
    headers: HEADERS
  })
  if (!editions.ok) return undefined

  const { entries = [] } = await editions.json()
  const english = entries.find(
    (entry) =>
      entry.covers?.some((id) => id > 0) &&
      (entry.languages ?? []).some((language) => language.key === '/languages/eng')
  )
  const coverId = english?.covers.find((id) => id > 0)

  return coverId ? readImage(`https://covers.openlibrary.org/b/id/${coverId}-M.jpg`) : undefined
}

mkdirSync(COVERS, { recursive: true })

const onDisk = new Set(
  readdirSync(COVERS)
    .filter((name) => name.endsWith('.jpg'))
    .map((name) => name.replace(/\.jpg$/, ''))
)

let fetched = 0
let missed = 0
const misses = []

for (const book of books) {
  if (onDisk.has(book.id) && !force) continue

  const image =
    (await byIsbn(book.isbn13)) ?? (await byIsbn(book.isbn10)) ?? (await bySearch(book))

  if (image) {
    writeFileSync(resolve(COVERS, `${book.id}.jpg`), image)
    onDisk.add(book.id)
    fetched++
    console.log(`  ✓ ${book.title} — ${book.author}`)
  } else {
    missed++
    misses.push(`${book.title} — ${book.author}`)
    console.log(`  · no cover: ${book.title} — ${book.author}`)
  }

  await sleep(PAUSE_MS)
}

const have = books.filter((book) => onDisk.has(book.id)).map((book) => book.id)

writeFileSync(
  MANIFEST,
  `/**
 * GENERATED by scripts/fetch-covers.mjs — the ids in public/covers.
 * Books absent from this list render the typographic fallback cover instead.
 */
export const coverIds: string[] = [
${have.map((id) => `  '${id}'`).join(',\n')}
]
`
)

console.log(`\nFetched ${fetched} new, ${missed} without a cover.`)
console.log(`Manifest: ${have.length}/${books.length} books have artwork.`)
if (misses.length) console.log(`\nNo cover found for:\n  ${misses.join('\n  ')}`)
